format_version = 4

[[images]]
width = 256
height = 256
data = [[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0], [0]]

[[images]]
width = 256
height = 256
data = [[0]]

[[images]]
width = 256
height = 256
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[sounds]]
notes = [36, 38, 40, 41, 43, 43, 43, 43, 43, 41, 40, 38, 36, 36, 36, 36, 36, 38, 40, 41, 43, 41, 40, 38, 36, 38, 40, 38, 36, 36, 36, 36]
tones = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
volumes = []
effects = [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
speed = 30

[[sounds]]
notes = [26, 33]
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = [25, 27, 29, 29, 29, 29, 29, 27, 25, 25]
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[musics]]
seqs = [[0]]

[[musics]]
seqs = []

[[musics]]
seqs = []

[[musics]]
seqs = []

[[musics]]
seqs = []

[[musics]]
seqs = []

[[musics]]
seqs = []

[[musics]]
seqs = []
